apiVersion: magalix.com/v1
kind: Policy
metadata:
  name: magalix.policies.containers-running-in-privileged-mode
spec:
  id: magalix.policies.containers-running-in-privileged-mode
  name: Containers Running In Privileged Mode
  description: |
    This Policy reports if containers are running in privileged mode. A privileged container is given access to all devices on the host. This allows the container nearly all the same access as processes running on the host.

    By default a container is not allowed to access any devices on the host, but a "privileged" container is given access to all devices on the host. This allows the container nearly all the same access as processes running on the host. This is useful for containers that want to use linux capabilities like manipulating the network stack and accessing devices.
  how_to_solve: |
    Look at the following path to see what the settings are. 
    ```
    ...
      spec:
        containers:
        - securityContext:
            privileged: <privilege>
    ```
    https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
  category: magalix.categories.pod-security
  severity: high
  targets: {kind: [Deployment, Job, ReplicationController, ReplicaSet, DaemonSet,
      StatefulSet, CronJob]}
  controls:
  - magalix.controls.pci-dss.2.2.4
  - magalix.controls.pci-dss.2.2.5
  - magalix.controls.cis-benchmark.5.2.1
  - magalix.controls.mitre-attack.4.1
  - magalix.controls.nist-800-190.3.3.1
  - magalix.controls.gdpr.25
  - magalix.controls.gdpr.32
  - magalix.controls.gdpr.24
  - magalix.controls.soc2-type-i.1.6.1
  tags: [pci-dss, cis-benchmark, mitre-attack, nist800-190, gdpr, soc2-type1, default]
  parameters:
  - name: privilege
    type: boolean
    required: true
    value: false
  - name: exclude_namespace
    type: string
    required: false
    value:
  - name: exclude_label_key
    type: string
    required: false
    value:
  - name: exclude_label_value
    type: string
    required: false
    value:

  code: |
    package magalix.advisor.podSecurity.privileged

    exclude_namespace := input.parameters.exclude_namespace
    privilege := input.parameters.privilege
    exclude_label_key := input.parameters.exclude_label_key
    exclude_label_value := input.parameters.exclude_label_value

    violation[result] {
      some i
      isExcludedNamespace == false
      not exclude_namespace == controller_input.metadata.namespace
      not exclude_label_value == controller_input.metadata.labels[exclude_label_key]
      container := controller_spec.containers[i]
      security_context_priv := container.securityContext.privileged
      not security_context_priv == privilege
      result = {
        "issue detected": true,
        "msg": sprintf("Container should set privileged to '%v'; detected '%v'", [privilege, security_context_priv]),
        "violating_key": sprintf("spec.template.spec.containers[%v].securityContext.privileged", [i]),
        "recommended_value": privilege
      }
    }

    isExcludedNamespace  = true {
      input.review.object.metadata.namespace == exclude_namespace
    }else = false {true}


    is_array_contains(array,str) {
      array[_] = str
    }

    # Controller input
    controller_input = input.review.object

    # controller_container acts as an iterator to get containers from the template
    controller_spec = controller_input.spec.template.spec {
      contains_kind(controller_input.kind, {"StatefulSet" , "DaemonSet", "Deployment", "Job"})
    } else = controller_input.spec {
      controller_input.kind == "Pod"
    } else = controller_input.spec.jobTemplate.spec.template.spec {
      controller_input.kind == "CronJob"
    }

    contains_kind(kind, kinds) {
      kinds[_] = kind
    }